name: kvm_pseries_bringup
nested: false
script: src/guest_bringup
params:
  accelerator: kvm
  machine: pseries
  memory: 8096
  cpu: POWER11
  vcpus: 16
  qcow_path: ./guests/qcows/large-fedora43.qcow2
  os_variant: fedora41
  name: fedora43-virtualpilot-kvm-pseries
  username: root
  password: "123456"
  host_kernel: false
  kernel: null
  initrd: null
  cmdline: null
  boot_timeout: 40
  virt_install_timeout: 10
