name: nested_kvm_pseries_bringup
nested: true
script: guest_bringup
params:
  l0_name: fedora43-virtualpilot-tcg-pseries
  l0_username: root
  l0_password: "123456"
  l0_location: /home/VirtualPilot/
  host_virtualpilot: virtual-pilot.py
  host_orchestrator: orchestrator.py
  nested_guest_image: guests/qcows/small-fedora43.qcow2
  host_script: src/guest_bringup.py
  host_suite: config/suites/nested_kvm_pseries_bringup.yaml
  nested_guest_image: guests/qcows/small-fedora43.qcow2
  scp_guest: true
  cleanup: true

  accelerator: kvm
  machine: pseries
  memory: 4096
  vcpus: 8
  cpu: POWER11
  qcow_path: small-fedora43.qcow2
  os_variant: fedora41
  name: fedora43-virtualpilot-kvm-pseries
  username: root
  password: "123456"
  qemu-extra-args: ""
  features: ""
  host_kernel: false
  kernel: null
  initrd: null
  cmdline: null
  boot_timeout: 500
  virt_install_timeout: 140
