name: tcg_pseries_bringup
nested: false
script: src/guest_bringup
params:
  accelerator: tcg
  machine: pseries
  memory: 8096
  vcpus: 16
  cpu: POWER11
  qcow_path: ./guests/qcows/large-fedora43.qcow2
  os_variant: fedora41
  name: fedora43-virtualpilot-tcg-pseries
  username: root
  password: "123456"
  qemu-extra-args: ""
  features: ""
  host_kernel: false
  kernel: null
  initrd: null
  cmdline: null
  boot_timeout: 240
  virt_install_timeout: 10
